node {

    //  create a variable
    def commit_id

    stage('Preparation') {
        // checkout and do git clone of this docker-demo in jenkins
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id" // 1. get the commit id > 2. put it in a file .git/commit-id in this case
        commit_id = readFile('.git/commit-id').trim() // store the id in the def commit_id and read the file from the temp .git/commit-id file
    }
    
    stage('test') {
        nodejs(nodeJSInstallationName: 'nodejs') {
            sh 'npm install --only=dev'
            sh 'npm test'
        }
    }

    stage('docker build/push') {
        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
            def app = docker.build("valmeza/docker-example:${commit_id}", ".").push();
        }
    }
}