web:
  build: .
  command: node index-db.js
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    MYSQL_DATABASE: docker_db
    MYSQL_USER: dockerUser
    MYSQL_PASSWORD: Sup3rS3cure***
    MYSQL_HOST: db
db:
  image: orchardup/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: docker_db
    MYSQL_USER: dockerUser
    MYSQL_PASSWORD: Sup3rS3cure***